[package]
name = "gorust"
version = "0.1.2"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
godot = "0.2.0"
mvecops = { path = "../mvecops" }

[target.aarch64-linux-android]
linker = "lld"